spring: 
  application: 
    name: SpringbootAWSsample

server:
  port: 9001
  
amazonProperties:
  endpointUrl: https://s3.amazonaws.com
  accessKey: [your access key]
  secretKey: [your secret key]
  bucketName: [your bucket]